name: MobCapturer
version: ${project.version}
author: TheBusyBiscuit
description: 黏液科技附加「生物捕捉器」繁體中文版。
website: https://github.com/TheBusyBiscuit/MobCapturer

main: io.github.thebusybiscuit.mobcapturer.MobCapturer
depend: [Slimefun]

api-version: 1.16
