name: MobCapturer
version: ${project.version}
author: TheBusyBiscuit
description: 此插件為繁體翻譯版, 原作者"TheBusyBiscuit".
website: https://github.com/TheBusyBiscuit/MobCapturer

main: io.github.thebusybiscuit.mobcapturer.MobCapturer
depend: [Slimefun]

api-version: 1.14